language: python
python:
  - "2.7"
  - "3.8"

git:
  depth: 1

install:
  - pip install flake8

script:
  - python -O -m compileall ./src/
  - find ./po -type f -name "*.po" -print -exec msgfmt {} -o {}.mo \;
  - flake8 --ignore=W191,W504,E126,E127,E128,E501 --show-source --exclude=./src/compat.py,./test/enigma.py,./test/try_plugin.py
  - flake8 --ignore=W191,E501,F821 --show-source --filename=./test/try_plugin.py
  - flake8 --ignore=W191,F401,E128,E402 --show-source --filename=./test/enigma.py
  - flake8 --ignore=W191,F821,F401 --show-source --filename=./src/compat.py
  - bash ./test/ci_fix.sh
  - pytest -rx -v
